### ISSUE TITLE
Is there a BOM to enable parts ordering?

### ISSUE THREAD

**Issue by 84ace** [oelprinz-org/BL49SP#3]
Hi,

I noticed that the BOM and parts list can't really be used to identify the parts needed to assemble the board. Is there a parts reference somewhere so that I can order the parts needed.

Also, is there a KiCad .pro somewhere so that changes can be made?

Cheers,
Acea

**Comment by chaoschris** [comment]
Hi Acea,
what is wrong with that partlist.txt in
https://raw.githubusercontent.com/oelprinz-org/BL49SP/master/hardware/V0.0.2/partlist.txt  ?

C1       1n               C-EUC0603       C0603            rcl                     1
C2       18p             C-EUC0603       C0603            rcl                     1
C3       18p             C-EUC0603       C0603            rcl                     1
C4       22u             C-EUC0805       C0805            rcl                     1
C5       1u               C-EUC0603       C0603            rcl                     1
.......

You can see clearly the part descriptor, the value and the package?

The board was designed in Eagle and at the moment we won't release the sources.
But if you have any suggestions for improvements we are always open for it.
Best regards,
Chris

**Comment by 84ace** [comment]
I'm not sure what I was expecting to be honest. Maybe just cap voltage and
ESR ratings, maybe part numbers/links at a stretch? Thanks.

**Comment by chaoschris** [comment]
Added two new sheets (.ods and .xlsx) with the part numbers and values.
You can find them in hardware/V0.0.2/bom/
[BOM_BL49SP_V0.0.2g.zip](https://github.com/oelprinz-org/BL49SP/files/5113166/BOM_BL49SP_V0.0.2g.zip)

**Comment by 84ace** [comment]
Legend! Thanks.

**Comment by chaoschris** [comment]
Detailed BOM added
