### ISSUE TITLE
Connector types

### ISSUE THREAD

**Issue by h2oo2h** [oelprinz-org/BL49SP#4]
What type of connectors do you use for sensor and supply?

**Comment by chaoschris** [comment]
Hello,
needed Connectors and Pins are Molex Mini-Fit Jr 5569 :
1x Pin Header 2x4P: 3930-1080
1x Pin Header 2x3P: 3930-1060
1x Contact housing female 2x4P: 3901-2085
1x Contact housing female 2x3P: 3901-2065
14x Crimp socket Female: 3900-0039

Best regards,
Chris


Zitat von h2oo2h <notifications@github.com>:

**Comment by chaoschris** [comment]
added the information now:
https://github.com/oelprinz-org/BL49SP/blob/master/hardware/V0.0.2/connectors.txt
