### ISSUE TITLE
Stuck on preheat

### ISSUE THREAD

**Issue by dener4321** [oelprinz-org/BL49SP#5]
```
	/* one step every second */
	if ((Abl.Tick - Abl.LastHeatTick) >= PROBE_PREHEAT_PERIOD)
	{
		/* Toggle heater LED */
		Out.Led2 ^= 1;
		/* Check if we have reached end phase */
		if ((Out.Heater >= end) || (In.UR < Abl.UROpt))
		{
			Abl.Mode = RUNNING;
		}
		else
		{
			Out.Heater += step;
			/* Limit heater voltage to end pulse width */
			if (Out.Heater > end) Out.Heater = end;
		}		
		/* Save tick count */
		Abl.LastHeatTick = Abl.Tick
```

I seem to have encountered a problem in this code.
Out.heater += step
For example if you add 252 + 7 it won't give 259 it will give 3 because the variable is of type uint8 it goes up to 255 only. Then it will restart the heating process.

**Comment by chaoschris** [comment]
Have you tested the corrected version of the software?

**Comment by dener4321** [comment]
> Have you tested the corrected version of the software?

yes it is working
